# Generated by Django 3.0.4 on 2020-03-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200310_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
